server:
  port: 8084
    
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: https://github.com/alejorcode/microservices.git
          search-paths: configurations
